#!/bin/sh

set -e

if [ ! -f /etc/apache2/ssl/server.crt ]; then
  openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/server.key -out /etc/apache2/ssl/server.crt -subj "/C=PL/ST=SUPLA/L=SUPLA/O=SUPLA/CN=SUPLA"
fi

if [ -n "${MAILER_HOST:-}" ]; then
  echo "[WARN] You are using deprecated e-mail configuration. Please use MAILER_DSN environment variable to configure it."
fi

ENV_MAPPINGS="
CLOUD_DOMAIN:SUPLA_HOST_ADDRESS
SECRET:APP_SECRET
FIRST_USER_EMAIL:SUPLA_FIRST_USER_EMAIL
FIRST_USER_PASSWORD:SUPLA_FIRST_USER_PASSWORD
RECAPTCHA_PUBLIC_KEY:GOOGLE_RECAPTCHA_SITE_KEY
RECAPTCHA_PRIVATE_KEY:GOOGLE_RECAPTCHA_SECRET
MAILER_FROM:SUPLA_MAILER_FROM
ADMIN_EMAIL:SUPLA_ADMIN_EMAIL
REQUIRE_REGULATIONS_ACCEPTANCE:SUPLA_REQUIRE_REGULATIONS_ACCEPTANCE
REQUIRE_COOKIE_POLICY_ACCEPTANCE:SUPLA_REQUIRE_COOKIE_POLICY_ACCEPTANCE
BRUTE_FORCE_AUTH_PREVENTION_ENABLED:SUPLA_BRUTE_FORCE_AUTH_PREVENTION_ENABLED
ACCOUNTS_REGISTRATION_ENABLED:SUPLA_ACCOUNTS_REGISTRATION_ENABLED
MQTT_BROKER_ENABLED:SUPLA_MQTT_BROKER_ENABLED
MQTT_BROKER_HOST:SUPLA_MQTT_BROKER_HOST
MQTT_BROKER_PORT:SUPLA_MQTT_BROKER_PORT
MQTT_BROKER_TLS:SUPLA_MQTT_BROKER_TLS
MQTT_BROKER_USERNAME:SUPLA_MQTT_BROKER_USERNAME
MQTT_BROKER_PASSWORD:SUPLA_MQTT_BROKER_PASSWORD
MQTT_BROKER_CLIENT_ID:SUPLA_MQTT_BROKER_CLIENT_ID
"

for mapping in $ENV_MAPPINGS; do
  old_name=$(echo "$mapping" | cut -d: -f1)
  new_name=$(echo "$mapping" | cut -d: -f2)

  eval old_value=\$${old_name}
  eval new_value=\$${new_name}

  if [ "${old_value}" != "" ]; then
    if [ "${new_value}" != "" ]; then
      echo "[WARN] Both ${old_name} and ${new_name} are set. Using ${new_name} and ignoring ${old_name}."
    else
      echo "[WARN] You are using deprecated ${old_name} environment variable. Please use ${new_name} instead."
      export ${new_name}="${old_value}"
    fi
  fi
done

cat > /var/www/cloud/.env.local <<EOF
APP_ENV=${APP_ENV:-prod}
APP_DEBUG=${APP_DEBUG:-0}
APP_SECRET=${APP_SECRET:-}
DATABASE_HOST=${DATABASE_HOST:-supla-db}
DATABASE_PORT=${DATABASE_PORT:-3306}
DATABASE_NAME=${DATABASE_NAME:-supla}
DATABASE_USER=${DATABASE_USER:-supla}
DATABASE_PASSWORD=${DATABASE_PASSWORD:-}
DATABASE_TSDB_URL=${DATABASE_TSDB_URL:-}
DATABASE_FOR_LOGS=${DATABASE_FOR_LOGS:-mariadb}
SUPLA_HOST_ADDRESS=${SUPLA_HOST_ADDRESS:-}
MAILER_DSN=${MAILER_DSN:-}
SUPLA_MAILER_FROM=${SUPLA_MAILER_FROM:-}
SUPLA_ADMIN_EMAIL=${SUPLA_ADMIN_EMAIL:-}
SUPLA_REQUIRE_REGULATIONS_ACCEPTANCE=${SUPLA_REQUIRE_REGULATIONS_ACCEPTANCE:-true}
SUPLA_REQUIRE_COOKIE_POLICY_ACCEPTANCE=${SUPLA_REQUIRE_COOKIE_POLICY_ACCEPTANCE:-true}
SUPLA_BRUTE_FORCE_AUTH_PREVENTION_ENABLED=${SUPLA_BRUTE_FORCE_AUTH_PREVENTION_ENABLED:-true}
SUPLA_ACCOUNTS_REGISTRATION_ENABLED=${SUPLA_ACCOUNTS_REGISTRATION_ENABLED:-true}
SUPLA_MQTT_BROKER_ENABLED=${SUPLA_MQTT_BROKER_ENABLED:-false}
SUPLA_MQTT_BROKER_HOST=${SUPLA_MQTT_BROKER_HOST:-}
SUPLA_MQTT_BROKER_PORT=${SUPLA_MQTT_BROKER_PORT:-8883}
SUPLA_MQTT_BROKER_TLS=${SUPLA_MQTT_BROKER_TLS:-true}
SUPLA_MQTT_BROKER_USERNAME=${SUPLA_MQTT_BROKER_USERNAME:-}
SUPLA_MQTT_BROKER_PASSWORD=${SUPLA_MQTT_BROKER_PASSWORD:-}
SUPLA_MQTT_BROKER_CLIENT_ID=${SUPLA_MQTT_BROKER_CLIENT_ID:-}
GOOGLE_RECAPTCHA_SITE_KEY=${GOOGLE_RECAPTCHA_SITE_KEY:-}
GOOGLE_RECAPTCHA_SECRET=${GOOGLE_RECAPTCHA_SECRET:-}
EOF

chmod 600 /var/www/cloud/.env.local
chown www-data:www-data /var/www/cloud/.env.local

rm -fr var/cache/*
php bin/console supla:initialize
php bin/console cache:warmup
chown -hR www-data:www-data var

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
