post_max_size = 8M
upload_max_filesize = 5M
expose_php = Off

opcache.memory_consumption = 192
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 10000
opcache.revalidate_freq = 0
opcache.enable_cli = 1
opcache.validate_timestamps = 0

error_reporting = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED
display_errors = Off
log_errors = On

date.timezone = UTC
