services:
  supla-cloud:
    container_name: ${COMPOSE_PROJECT_NAME}-cloud
    init: true
    restart: unless-stopped
    build: ./cloud
    env_file:
      - .env
    volumes:
      - ./ssl/cloud:/etc/apache2/ssl:z
      - ${VOLUME_DATA:-./var}/cloud-local:/var/www/cloud/var/local
      - ${VOLUME_DATA:-./var}/cloud-logs:/var/www/cloud/var/log
      - supla-server-socket:/var/run/supla:z
    logging:
      options:
        max-size: 50m
    depends_on:
      - supla-db

  supla-db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: unless-stopped
    image: ${DATABASE_IMAGE}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: supla
      MYSQL_USER: supla
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${VOLUME_DATA:-./var}/mysql:/var/lib/mysql:z
      - ./db:/etc/mysql/conf.d
    logging:
      options:
        max-size: 50m

  supla-server:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    restart: unless-stopped
    build: ./server
    env_file:
      - .env
    volumes:
      - ./ssl/server:/etc/supla-server/ssl:z
      - supla-server-socket:/var/run/supla
    ports:
      - "2016:2016"
      - "2015:2015"
    logging:
      options:
        max-size: 50m
    depends_on:
      - supla-cloud

volumes:
  supla-server-socket: {}
